name: apppocsa
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  material_design_icons_flutter: 3.2.3595
  cupertino_icons: ^0.1.3
  rxdart: ^0.24.0
  observable: ^0.22.2
  http:
  redux: ^3.0.0
  flutter_redux: ^0.5.3
  redux_thunk: ^0.2.1
  redux_logging: ^0.3.0
  flutter_svg: ^0.17.4
  modal_progress_hud: ^0.1.3
  rflutter_alert: ^1.0.3
  carousel_pro: ^1.0.0
  nima: ^1.0.5
  slimy_card: ^1.0.4
  card_selector: ^0.1.0
  photo_view: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - icons/icons8-redux.svg
    - icons/accenture.png
    - images/arquitectura1.png
    - images/nima/Hop.nima
    - images/nima/Hop.png
    - images/redux.png
    - images/reduxMiddleware.png
    - images/MisCreditos1.png
    - images/MisCreditos2.png
    - images/MisCuentas1.png
    - images/MisCuentas2.png
    - images/ConNosotros.png
    - images/Ayuda1.png
    - images/calm.jpg
    - images/vistaArchitecture.jpeg
    - images/aggresive.jpg
    - lib/src/utils/in.json
    - lib/src/utils/in2.json
    - images/borde.png
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: SansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
    - family: rms
      fonts:
        - asset: fonts/RemachineScript.ttf
    - family: LBF
      fonts:
        - asset: fonts/LibreFranklin-Bold.ttf
    - family: LBFE
      fonts:
        - asset: fonts/LibreFranklin-ExtraBold.ttf
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
